use_frameworks!

platform :ios, '9.0'

target 'HeySurLib_Example' do
  pod 'HeySurLib', :path => '../'

  target 'HeySurLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
